repositories:
  - name: bitnami
    url: https://mirror.yandex.ru/helm/charts.bitnami.com

releases:
  - name: layout-ui
    labels:
      app: layout-ui
    wait: true
    chart: bitnami/nginx
    # after 15.3.5 our docker file or setup can no longer start, need to investigate what is wrong for the newer versions
    version: 15.3.5
    values:
      - values.yaml
      - image:
          tag: "{{ .StateValues.image.tag }}"
      - ingress:
          hostname: "{{ .StateValues.ingress.hostname }}"
          annotations:
            # configuration-snippet is used to redirect from short to original domain
            nginx.ingress.kubernetes.io/configuration-snippet: "{{ .StateValues.redirectAnnotation }}"
          extraHosts:
            # additional host needed to set up redirect
            - name: "{{ .StateValues.ingress.extraHosts.name }}"
              path: "{{ .StateValues.ingress.extraHosts.path }}"
          extraTls:
          - hosts:
              - "{{ .StateValues.ingress.extraTls.hosts.name }}"
            secretName: "{{ .StateValues.ingress.extraTls.secretName }}"
