repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: layout-ui
    labels:
      app: layout-ui
    wait: true
    chart: bitnami/nginx
    # after 15.3.5 our docker file or setup can no longer start, need to investigate what is wrong for the newer versions
    version: 15.3.5
    values:
      - values.yaml
    set:
      - name: image.tag
        value: {{ github.sha }} 
      - name: ingress.enabled
        value: true 
      - name: ingress.hostname
        value: {{ secrets.DEV_HOST }}
